
# /home/stephen/continuum/pyrewrite/rewrite/dsl/dyacc.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '{\x8dt\xbc\xd9\x87\x81\xf1\xae\xe4\xa49]\xae`\xfe'
    
_lr_action_items = {'COMB':([6,9,10,11,12,13,14,15,17,20,21,22,23,31,35,37,39,40,],[-29,-10,-18,-13,-17,-16,-28,-12,-11,-15,-14,31,-8,-29,-25,-22,31,-19,]),'STRING':([5,6,18,19,24,25,31,36,38,41,],[14,14,14,14,14,14,14,14,14,14,]),'INT':([5,6,18,19,24,25,31,36,38,41,],[12,12,12,12,12,12,12,12,12,12,]),'DOUBLE':([5,6,18,19,24,25,31,36,38,41,],[13,13,13,13,13,13,13,13,13,13,]),']':([9,10,11,12,13,14,15,17,19,20,21,26,29,30,35,37,38,40,43,],[-10,-18,-13,-17,-16,-28,-12,-11,-29,-15,-14,-9,-23,37,-25,-22,-29,-19,-24,]),',':([9,10,11,12,13,14,15,17,18,19,20,21,24,26,27,28,29,30,32,33,35,36,37,38,40,41,42,43,44,],[-10,-18,-13,-17,-16,-28,-12,-11,-29,-29,-15,-14,-29,-9,36,-26,-23,38,-20,41,-25,-29,-22,-29,-19,-29,36,38,41,]),')':([9,10,11,12,13,14,15,17,18,20,21,24,26,27,28,32,33,35,36,37,40,41,42,44,],[-10,-18,-13,-17,-16,-28,-12,-11,-29,-15,-14,-29,-9,35,-26,-20,40,-25,-29,-22,-19,-29,-27,-21,]),'ARROW':([5,9,10,11,12,13,14,15,16,17,20,21,35,37,40,],[-29,-10,-18,-13,-17,-16,-28,-12,25,-11,-15,-14,-25,-22,-19,]),'(':([5,6,9,10,12,13,18,19,24,25,31,36,38,41,],[18,18,24,-18,-17,-16,18,18,18,18,18,18,18,18,]),'[':([5,6,18,19,24,25,31,36,38,41,],[19,19,19,19,19,19,19,19,19,19,]),':':([1,],[5,]),'=':([1,],[6,]),'$end':([2,3,4,6,7,8,9,10,11,12,13,14,15,17,20,21,22,23,25,31,34,35,37,39,40,],[-4,-3,0,-29,-2,-1,-10,-18,-13,-17,-16,-28,-12,-11,-15,-14,-6,-8,-29,-29,-5,-25,-22,-7,-19,]),'NAME':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,31,34,35,36,37,38,39,40,41,],[1,-4,-3,1,10,10,-2,-1,-10,-18,-13,-17,-16,-28,-12,-11,10,10,-15,-14,-6,-8,10,10,10,-5,-25,10,-22,10,-7,-19,10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tuple_value':([18,36,],[27,42,]),'term':([5,6,18,19,24,25,31,36,38,41,],[9,9,9,9,9,9,9,9,9,9,]),'string':([5,6,18,19,24,25,31,36,38,41,],[21,21,21,21,21,21,21,21,21,21,]),'tuple':([5,6,18,19,24,25,31,36,38,41,],[11,11,11,11,11,11,11,11,11,11,]),'expr':([18,19,24,36,38,41,],[28,29,32,28,29,32,]),'strategy_value':([6,31,],[22,39,]),'list':([5,6,18,19,24,25,31,36,38,41,],[15,15,15,15,15,15,15,15,15,15,]),'rule':([0,4,],[3,8,]),'strategy':([0,4,],[2,7,]),'appl':([5,6,18,19,24,25,31,36,38,41,],[17,17,17,17,17,17,17,17,17,17,]),'list_value':([19,38,],[30,43,]),'value':([5,6,18,19,24,25,31,36,38,41,],[16,23,26,26,26,34,23,26,26,26,]),'definitions':([0,],[4,]),'empty':([5,6,18,19,24,25,31,36,38,41,],[20,20,20,20,20,20,20,20,20,20,]),'appl_value':([24,41,],[33,44,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> definitions","S'",1,None,None,None),
  ('definitions -> definitions rule','definitions',2,'p_definitions1','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',137),
  ('definitions -> definitions strategy','definitions',2,'p_definitions1','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',138),
  ('definitions -> rule','definitions',1,'p_definitions2','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',142),
  ('definitions -> strategy','definitions',1,'p_definitions2','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',143),
  ('rule -> NAME : value ARROW value','rule',5,'p_rule','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',149),
  ('strategy -> NAME = strategy_value','strategy',3,'p_strategy','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',155),
  ('strategy_value -> strategy_value COMB strategy_value','strategy_value',3,'p_strategy_value1','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',160),
  ('strategy_value -> value','strategy_value',1,'p_strategy_value2','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',170),
  ('expr -> value','expr',1,'p_expr','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',176),
  ('value -> term','value',1,'p_value','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',182),
  ('value -> appl','value',1,'p_value','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',183),
  ('value -> list','value',1,'p_value','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',184),
  ('value -> tuple','value',1,'p_value','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',185),
  ('value -> string','value',1,'p_value','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',186),
  ('value -> empty','value',1,'p_value','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',187),
  ('term -> DOUBLE','term',1,'p_term_double','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',193),
  ('term -> INT','term',1,'p_term_int','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',197),
  ('term -> NAME','term',1,'p_term_term','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',201),
  ('appl -> term ( appl_value )','appl',4,'p_appl','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',207),
  ('appl_value -> expr','appl_value',1,'p_appl_value1','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',211),
  ('appl_value -> appl_value , appl_value','appl_value',3,'p_appl_value2','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',218),
  ('list -> [ list_value ]','list',3,'p_list','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',224),
  ('list_value -> expr','list_value',1,'p_list_value1','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',228),
  ('list_value -> list_value , list_value','list_value',3,'p_list_value2','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',235),
  ('tuple -> ( tuple_value )','tuple',3,'p_tuple','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',241),
  ('tuple_value -> expr','tuple_value',1,'p_tuple_value1','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',245),
  ('tuple_value -> tuple_value , tuple_value','tuple_value',3,'p_tuple_value2','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',252),
  ('string -> STRING','string',1,'p_string','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',258),
  ('empty -> <empty>','empty',0,'p_empty','/home/stephen/continuum/pyrewrite/rewrite/dsl/parse.py',264),
]
